version: "3"

networks:
  intra:
    name: intra
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: none
      o: bind
      # device: /home/sangcpar/data/wordpress
      device: /Users/sangcpar/Desktop/inceotion/data/wordpress
  db:
    driver: local
    name: db
    driver_opts:
      type: none
      o: bind
      # device: /home/sangcpar/data/mariadb
      device: /Users/sangcpar/Desktop/inceotion/data/mariadb

services:
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - intra
    restart: always
    tty: true

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - "9000"
    env_file:
      - .env
    depends_on:
      - mariadb
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    restart: always
    tty: true

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - intra
    restart: always
    tty: true
